# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_censo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.DateField(auto_now=True)),
                ('resguardo', models.IntegerField(blank=True)),
                ('comunidad_indigena', models.IntegerField(blank=True)),
                ('familia', models.IntegerField()),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('RC', 'Registro civil'), ('NUIP', 'Número único de identificación personal'), ('TI', 'TARJETA_IDENTIDAD')], default='CC', max_length=6)),
                ('numero_documento', models.IntegerField()),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('parentesco', models.CharField(choices=[('PA', 'Padre'), ('MA', 'Madre'), ('CO', 'Cónyugue'), ('HE', 'Hermano (a)'), ('CA', 'Cabeza de Familia'), ('ES', 'Esposa'), ('HI', 'Hijo (a)'), ('YR', 'Yerno (a)'), ('NU', 'Nuera'), ('SU', 'Suegro (a)'), ('SO', 'Sobrino (a)'), ('CU', 'Cuñado (a)'), ('TI', 'Tío (a)'), ('AB', 'Abuelo (a)')], default='CA', max_length=4)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado')], default='S', max_length=2)),
                ('profesion', models.IntegerField(blank=True)),
                ('escolaridad', models.CharField(choices=[('PR', 'Primaria'), ('SE', 'Secundaria'), ('UN', 'Universitaria'), ('NI', 'Ninguno')], default='PR', max_length=3)),
                ('integrantes', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=15)),
            ],
        ),
    ]
