# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='censo_archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='formatos/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_censo', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='registro_censo',
            name='comunidad_indigena',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registro_censo',
            name='familia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registro_censo',
            name='numero_documento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registro_censo',
            name='profesion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registro_censo',
            name='resguardo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
